name: pmg
services:
  site:
    build: .
    image: ghcr.io/paveloom-c/pmg:latest
    develop:
      watch:
        - path: landing
          action: rebuild
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  traefik:
    external: true
