name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: paveloom-pmg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Document
        run: nix develop --command bash -c "./document.bash"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: public
          single-commit: true
